version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    links:
      - redis
    env_file:
      - environment_variables.env
    volumes:
      - $LOG_DIR_HOST:$LOG_DIR_GUEST
  redis:
    image: redis
    ports:
      - "6379:6379"