version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    links:
      - redis
    env_file:
      - security_credentials.env
  redis:
    image: redis
    ports:
      - "6379:6379"