name: Remote SSH Deploy
on:
  push:
    branches:
      - github-action-update
jobs:

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
      - name: Set up JDK 17
        uses: actions/setup-java@v3.5.0
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Run tests
        run: mvn test

  posttest:
    needs: test
    name: Post tests check
    runs-on: ubuntu-latest
    steps:
      - name: Printing out message
        run: echo ====Test complete====